### ISSUE TITLE
Stack trace on install 

### ISSUE THREAD

**Issue by jelford** [git-hooks/git-hooks#16]
Version: 1.1.3
Platform: linux_amd64

On a fresh PC, I just unpacked the binaries onto my path and ran `git hooks install`

I did have an existing pre-commit hook.

The result on my file system were:
- `.git/hooks` has been backed up to `.git/hooks.old`
- `.git/hooks` seems to have the new scripts installed

When I create `./githooks` and add files to it, `git hooks` correctly identifies them - and they're correctly invoked on commit.

So, the main problem is the stack (below). I'd be happy to jump in and take a look, but I don't have a go environment set up right now.

```
(venv_name) [jelford@host venv_name]$ git hooks install
Install applypatch-msg
Install commit-msg
Install post-applypatch
Install post-checkout
Install post-commit
Install post-merge
Install post-receive
Install pre-applypatch
Install pre-auto-gc
Install pre-commit
Install prepare-commit-msg
runtime: garbage collector found invalid heap pointer *(0xc20804a028+0x0)=0x1 s=nil
runtime: found *(0xc2080295a8+0x28) = 0xc20804a028+0x0
fatal error: bad pointer

runtime stack:
runtime.throw(0x9b3819)
    /usr/local/Cellar/go/1.4/libexec/src/runtime/panic.go:491 +0xad fp=0xc20802fa90 sp=0xc20802fa60
scanblock(0xc2080295a8, 0x240, 0x8917d4)
    /usr/local/Cellar/go/1.4/libexec/src/runtime/mgc0.c:412 +0x989 fp=0xc20802fbd0 sp=0xc20802fa90
scanframe(0xc20802fcd8, 0x0, 0xc200000301)
    /usr/local/Cellar/go/1.4/libexec/src/runtime/mgc0.c:719 +0x164 fp=0xc20802fc40 sp=0xc20802fbd0
runtime.gentraceback(0x4468d0, 0xc208028d50, 0x0, 0xc208000120, 0x0, 0x0, 0x7fffffff, 0xc20802fd88, 0x0, 0x0, ...)
    /usr/local/Cellar/go/1.4/libexec/src/runtime/traceback.go:311 +0x7a8 fp=0xc20802fd30 sp=0xc20802fc40
scanstack(0xc208000120)
    /usr/local/Cellar/go/1.4/libexec/src/runtime/mgc0.c:777 +0x21c fp=0xc20802fda0 sp=0xc20802fd30
markroot(0xc208010000, 0x5)
    /usr/local/Cellar/go/1.4/libexec/src/runtime/mgc0.c:553 +0xe7 fp=0xc20802fe00 sp=0xc20802fda0
runtime.parfordo(0xc208010000)
    /usr/local/Cellar/go/1.4/libexec/src/runtime/parfor.c:76 +0xb2 fp=0xc20802fe80 sp=0xc20802fe00
gc(0xc20802ffb8)
    /usr/local/Cellar/go/1.4/libexec/src/runtime/mgc0.c:1439 +0x25e fp=0xc20802ff98 sp=0xc20802fe80
runtime.gc_m()
    /usr/local/Cellar/go/1.4/libexec/src/runtime/mgc0.c:1368 +0xe0 fp=0xc20802ffd0 sp=0xc20802ff98
runtime.onM(0xc208012000)
    /usr/local/Cellar/go/1.4/libexec/src/runtime/asm_amd64.s:257 +0x68 fp=0xc20802ffd8 sp=0xc20802ffd0
runtime.mstart()
    /usr/local/Cellar/go/1.4/libexec/src/runtime/proc.c:818 fp=0xc20802ffe0 sp=0xc20802ffd8

goroutine 1 [garbage collection]:
runtime.switchtoM()
    /usr/local/Cellar/go/1.4/libexec/src/runtime/asm_amd64.s:198 fp=0xc208028d58 sp=0xc208028d50
runtime.gogc(0x7f1e00000000)
    /usr/local/Cellar/go/1.4/libexec/src/runtime/malloc.go:469 +0x1cf fp=0xc208028d90 sp=0xc208028d58
runtime.mallocgc(0x70, 0x790840, 0x0, 0x8)
    /usr/local/Cellar/go/1.4/libexec/src/runtime/malloc.go:341 +0x391 fp=0xc208028e40 sp=0xc208028d90
runtime.newobject(0x790840, 0xc2080316a8)
    /usr/local/Cellar/go/1.4/libexec/src/runtime/malloc.go:353 +0x49 fp=0xc208028e68 sp=0xc208028e40
github.com/wsxiaoys/terminal/color.compile(0x7deff0, 0x1, 0x0, 0x0)
    /Users/zhongchiyu/workspace/go/src/github.com/wsxiaoys/terminal/color/color.go:136 +0x118 fp=0xc208028f08 sp=0xc208028e68
github.com/wsxiaoys/terminal/color.compileValues(0xc208029050)
    /Users/zhongchiyu/workspace/go/src/github.com/wsxiaoys/terminal/color/color.go:157 +0xf0 fp=0xc208028fd0 sp=0xc208028f08
github.com/wsxiaoys/terminal/color.Print(0xc20803c780, 0x3, 0x4, 0xc20800b840, 0x0, 0x0)
    /Users/zhongchiyu/workspace/go/src/github.com/wsxiaoys/terminal/color/color.go:165 +0x159 fp=0xc208029050 sp=0xc208028fd0
main.(*Logger).Info(0xc20804c2d0, 0xc20800b840, 0x2, 0x2)
    /Users/zhongchiyu/workspace/go/src/github.com/git-hooks/git-hooks/logger.go:46 +0x1e6 fp=0xc2080290c8 sp=0xc208029050
main.(*Logger).Infoln(0xc20804c2d0, 0xc2080291e0, 0x1, 0x1)
    /Users/zhongchiyu/workspace/go/src/github.com/git-hooks/git-hooks/logger.go:62 +0x155 fp=0xc208029160 sp=0xc2080290c8
main.installInto(0xc208030db0, 0x4, 0x8535b0, 0x2b)
    /Users/zhongchiyu/workspace/go/src/github.com/git-hooks/git-hooks/cli.go:410 +0x400 fp=0xc2080293a8 sp=0xc208029160
main.install(0x1)
    /Users/zhongchiyu/workspace/go/src/github.com/git-hooks/git-hooks/cli.go:165 +0x3e9 fp=0xc2080294c0 sp=0xc2080293a8
runtime.call16(0x898d98, 0xc20804a028, 0x800000008)
    /usr/local/Cellar/go/1.4/libexec/src/runtime/asm_amd64.s:401 +0x45 fp=0xc2080294d8 sp=0xc2080294c0
reflect.Value.call(0x6cca60, 0x898d98, 0x13, 0x7d86f0, 0x4, 0xc20800a520, 0x1, 0x1, 0x0, 0x0, ...)
    /usr/local/Cellar/go/1.4/libexec/src/reflect/value.go:419 +0x10e5 fp=0xc2080297f0 sp=0xc2080294d8
reflect.Value.Call(0x6cca60, 0x898d98, 0x13, 0xc20800a520, 0x1, 0x1, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.4/libexec/src/reflect/value.go:296 +0xbc fp=0xc208029850 sp=0xc2080297f0
main.func·004(0xc2080880c0)
    /Users/zhongchiyu/workspace/go/src/github.com/git-hooks/git-hooks/util.go:55 +0x45 fp=0xc2080298a0 sp=0xc208029850
github.com/codegangsta/cli.Command.Run(0x7e2b30, 0x7, 0x7e2830, 0x1, 0x8298b0, 0x1e, 0x0, 0x0, 0x0, 0x0, ...)
    /Users/zhongchiyu/workspace/go/src/github.com/codegangsta/cli/command.go:113 +0x1038 fp=0xc208029c60 sp=0xc2080298a0
github.com/codegangsta/cli.(*App).Run(0xc20801e4e0, 0xc20800a000, 0x2, 0x2, 0x0, 0x0)
    /Users/zhongchiyu/workspace/go/src/github.com/codegangsta/cli/app.go:156 +0xcf7 fp=0xc208029ed8 sp=0xc208029c60
main.main()
    /Users/zhongchiyu/workspace/go/src/github.com/git-hooks/git-hooks/cli.go:80 +0x4d9 fp=0xc208029f98 sp=0xc208029ed8
runtime.main()
    /usr/local/Cellar/go/1.4/libexec/src/runtime/proc.go:63 +0xf3 fp=0xc208029fe0 sp=0xc208029f98
runtime.goexit()
    /usr/local/Cellar/go/1.4/libexec/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208029fe8 sp=0xc208029fe0

goroutine 2 [force gc (idle)]:
runtime.gopark(0x43e6d0, 0x9c1130, 0x7f8fd0, 0xf)
    /usr/local/Cellar/go/1.4/libexec/src/runtime/proc.go:130 +0x105 fp=0xc20801a798 sp=0xc20801a768
runtime.goparkunlock(0x9c1130, 0x7f8fd0, 0xf)
    /usr/local/Cellar/go/1.4/libexec/src/runtime/proc.go:136 +0x48 fp=0xc20801a7c0 sp=0xc20801a798
runtime.forcegchelper()
    /usr/local/Cellar/go/1.4/libexec/src/runtime/proc.go:99 +0xce fp=0xc20801a7e0 sp=0xc20801a7c0
runtime.goexit()
    /usr/local/Cellar/go/1.4/libexec/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801a7e8 sp=0xc20801a7e0
created by runtime.init·4
    /usr/local/Cellar/go/1.4/libexec/src/runtime/proc.go:87 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x43e6d0, 0x9c9c18, 0x7ee250, 0xd)
    /usr/local/Cellar/go/1.4/libexec/src/runtime/proc.go:130 +0x105 fp=0xc20801df98 sp=0xc20801df68
runtime.goparkunlock(0x9c9c18, 0x7ee250, 0xd)
    /usr/local/Cellar/go/1.4/libexec/src/runtime/proc.go:136 +0x48 fp=0xc20801dfc0 sp=0xc20801df98
runtime.bgsweep()
    /usr/local/Cellar/go/1.4/libexec/src/runtime/mgc0.go:98 +0xbc fp=0xc20801dfe0 sp=0xc20801dfc0
runtime.goexit()
    /usr/local/Cellar/go/1.4/libexec/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801dfe8 sp=0xc20801dfe0
created by gc
    /usr/local/Cellar/go/1.4/libexec/src/runtime/mgc0.c:1383

goroutine 4 [finalizer wait]:
runtime.gopark(0x43e6d0, 0x9c9c10, 0x7f8890, 0xe)
    /usr/local/Cellar/go/1.4/libexec/src/runtime/proc.go:130 +0x105 fp=0xc208019730 sp=0xc208019700
runtime.goparkunlock(0x9c9c10, 0x7f8890, 0xe)
    /usr/local/Cellar/go/1.4/libexec/src/runtime/proc.go:136 +0x48 fp=0xc208019758 sp=0xc208019730
runtime.runfinq()
    /usr/local/Cellar/go/1.4/libexec/src/runtime/malloc.go:727 +0xba fp=0xc2080197e0 sp=0xc208019758
runtime.goexit()
    /usr/local/Cellar/go/1.4/libexec/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080197e8 sp=0xc2080197e0
created by runtime.createfing
    /usr/local/Cellar/go/1.4/libexec/src/runtime/malloc.go:707 +0x5e
```

**Comment by CatTail** [comment]
Does this happens everytime?
Can you give me your OS information?

**Comment by jelford** [comment]
Yes, it does seem to happen on every install. The bad pointer addresses seem the same every time.

OS Info:

* Fedora 22 (64 bit)
* ```ldd``` just says it's not a dynamic executable (is that generally the case for all Go programs?)
* Kernel: 4.1.6-201
```
[jelford:new-repo]$ uname -a
Linux hostname 4.1.6-201.fc22.x86_64 #1 SMP Fri Sep 4 17:49:24 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Since there are no shared libraries, I guess it won't help to have info on my machine's standard library versions.

**Comment by JSteunou** [comment]
Same here, fresh project, no hooks before.

* Ubuntu 15.10 (64 bit)
* Kernel 4.2.0-30-generic

```
$ git hooks install
Install applypatch-msg
Install commit-msg
Install post-applypatch
Install post-checkout
Install post-commit
Install post-merge
Install post-receive
Install pre-applypatch
Install pre-auto-gc
Install pre-commit
Install prepare-commit-msg
runtime: garbage collector found invalid heap pointer *(0xc20804c028+0x0)=0x1 s=nil
runtime: found *(0xc20802d5a8+0x28) = 0xc20804c028+0x0
fatal error: bad pointer

runtime stack:
runtime.throw(0x9b3819)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/panic.go:491 +0xad fp=0x7ffed0db8360 sp=0x7ffed0db8330
scanblock(0xc20802d5a8, 0x240, 0x8917d4)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/mgc0.c:412 +0x989 fp=0x7ffed0db84a0 sp=0x7ffed0db8360
scanframe(0x7ffed0db85a8, 0x0, 0x7ffe00000301)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/mgc0.c:719 +0x164 fp=0x7ffed0db8510 sp=0x7ffed0db84a0
runtime.gentraceback(0x4468d0, 0xc20802cd50, 0x0, 0xc208000120, 0x0, 0x0, 0x7fffffff, 0x7ffed0db8658, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/traceback.go:311 +0x7a8 fp=0x7ffed0db8600 sp=0x7ffed0db8510
scanstack(0xc208000120)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/mgc0.c:777 +0x21c fp=0x7ffed0db8670 sp=0x7ffed0db8600
markroot(0xc208010000, 0x5)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/mgc0.c:553 +0xe7 fp=0x7ffed0db86d0 sp=0x7ffed0db8670
runtime.parfordo(0xc208010000)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/parfor.c:76 +0xb2 fp=0x7ffed0db8750 sp=0x7ffed0db86d0
gc(0x7ffed0db8888)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/mgc0.c:1439 +0x25e fp=0x7ffed0db8868 sp=0x7ffed0db8750
runtime.gc_m()
	/usr/local/Cellar/go/1.4/libexec/src/runtime/mgc0.c:1368 +0xe0 fp=0x7ffed0db88a0 sp=0x7ffed0db8868
runtime.onM(0x9c18b0)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/asm_amd64.s:257 +0x68 fp=0x7ffed0db88a8 sp=0x7ffed0db88a0
runtime.mstart()
	/usr/local/Cellar/go/1.4/libexec/src/runtime/proc.c:818 fp=0x7ffed0db88b0 sp=0x7ffed0db88a8

goroutine 1 [garbage collection]:
runtime.switchtoM()
	/usr/local/Cellar/go/1.4/libexec/src/runtime/asm_amd64.s:198 fp=0xc20802cd58 sp=0xc20802cd50
runtime.gogc(0x7f1200000000)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/malloc.go:469 +0x1cf fp=0xc20802cd90 sp=0xc20802cd58
runtime.mallocgc(0x70, 0x790840, 0x0, 0x8)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/malloc.go:341 +0x391 fp=0xc20802ce40 sp=0xc20802cd90
runtime.newobject(0x790840, 0xc2080336b8)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/malloc.go:353 +0x49 fp=0xc20802ce68 sp=0xc20802ce40
github.com/wsxiaoys/terminal/color.compile(0x7deff0, 0x1, 0x0, 0x0)
	/Users/zhongchiyu/workspace/go/src/github.com/wsxiaoys/terminal/color/color.go:136 +0x118 fp=0xc20802cf08 sp=0xc20802ce68
github.com/wsxiaoys/terminal/color.compileValues(0xc20802d050)
	/Users/zhongchiyu/workspace/go/src/github.com/wsxiaoys/terminal/color/color.go:157 +0xf0 fp=0xc20802cfd0 sp=0xc20802cf08
github.com/wsxiaoys/terminal/color.Print(0xc20803e880, 0x3, 0x4, 0xc20800b7c0, 0x0, 0x0)
	/Users/zhongchiyu/workspace/go/src/github.com/wsxiaoys/terminal/color/color.go:165 +0x159 fp=0xc20802d050 sp=0xc20802cfd0
main.(*Logger).Info(0xc20804e2d0, 0xc20800b7c0, 0x2, 0x2)
	/Users/zhongchiyu/workspace/go/src/github.com/git-hooks/git-hooks/logger.go:46 +0x1e6 fp=0xc20802d0c8 sp=0xc20802d050
main.(*Logger).Infoln(0xc20804e2d0, 0xc20802d1e0, 0x1, 0x1)
	/Users/zhongchiyu/workspace/go/src/github.com/git-hooks/git-hooks/logger.go:62 +0x155 fp=0xc20802d160 sp=0xc20802d0c8
main.installInto(0xc208032dc0, 0x4, 0x8535b0, 0x2b)
	/Users/zhongchiyu/workspace/go/src/github.com/git-hooks/git-hooks/cli.go:410 +0x400 fp=0xc20802d3a8 sp=0xc20802d160
main.install(0x1)
	/Users/zhongchiyu/workspace/go/src/github.com/git-hooks/git-hooks/cli.go:165 +0x3e9 fp=0xc20802d4c0 sp=0xc20802d3a8
runtime.call16(0x898d98, 0xc20804c028, 0x800000008)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/asm_amd64.s:401 +0x45 fp=0xc20802d4d8 sp=0xc20802d4c0
reflect.Value.call(0x6cca60, 0x898d98, 0x13, 0x7d86f0, 0x4, 0xc20800a520, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.4/libexec/src/reflect/value.go:419 +0x10e5 fp=0xc20802d7f0 sp=0xc20802d4d8
reflect.Value.Call(0x6cca60, 0x898d98, 0x13, 0xc20800a520, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4/libexec/src/reflect/value.go:296 +0xbc fp=0xc20802d850 sp=0xc20802d7f0
main.func·004(0xc2080800c0)
	/Users/zhongchiyu/workspace/go/src/github.com/git-hooks/git-hooks/util.go:55 +0x45 fp=0xc20802d8a0 sp=0xc20802d850
github.com/codegangsta/cli.Command.Run(0x7e2b30, 0x7, 0x7e2830, 0x1, 0x8298b0, 0x1e, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/zhongchiyu/workspace/go/src/github.com/codegangsta/cli/command.go:113 +0x1038 fp=0xc20802dc60 sp=0xc20802d8a0
github.com/codegangsta/cli.(*App).Run(0xc20801e410, 0xc20800a000, 0x2, 0x2, 0x0, 0x0)
	/Users/zhongchiyu/workspace/go/src/github.com/codegangsta/cli/app.go:156 +0xcf7 fp=0xc20802ded8 sp=0xc20802dc60
main.main()
	/Users/zhongchiyu/workspace/go/src/github.com/git-hooks/git-hooks/cli.go:80 +0x4d9 fp=0xc20802df98 sp=0xc20802ded8
runtime.main()
	/usr/local/Cellar/go/1.4/libexec/src/runtime/proc.go:63 +0xf3 fp=0xc20802dfe0 sp=0xc20802df98
runtime.goexit()
	/usr/local/Cellar/go/1.4/libexec/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20802dfe8 sp=0xc20802dfe0

goroutine 2 [force gc (idle)]:
runtime.gopark(0x43e6d0, 0x9c1130, 0x7f8fd0, 0xf)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/proc.go:130 +0x105 fp=0xc20801a798 sp=0xc20801a768
runtime.goparkunlock(0x9c1130, 0x7f8fd0, 0xf)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/proc.go:136 +0x48 fp=0xc20801a7c0 sp=0xc20801a798
runtime.forcegchelper()
	/usr/local/Cellar/go/1.4/libexec/src/runtime/proc.go:99 +0xce fp=0xc20801a7e0 sp=0xc20801a7c0
runtime.goexit()
	/usr/local/Cellar/go/1.4/libexec/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801a7e8 sp=0xc20801a7e0
created by runtime.init·4
	/usr/local/Cellar/go/1.4/libexec/src/runtime/proc.go:87 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x43e6d0, 0x9c9c18, 0x7ee250, 0xd)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/proc.go:130 +0x105 fp=0xc20801df98 sp=0xc20801df68
runtime.goparkunlock(0x9c9c18, 0x7ee250, 0xd)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/proc.go:136 +0x48 fp=0xc20801dfc0 sp=0xc20801df98
runtime.bgsweep()
	/usr/local/Cellar/go/1.4/libexec/src/runtime/mgc0.go:98 +0xbc fp=0xc20801dfe0 sp=0xc20801dfc0
runtime.goexit()
	/usr/local/Cellar/go/1.4/libexec/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20801dfe8 sp=0xc20801dfe0
created by gc
	/usr/local/Cellar/go/1.4/libexec/src/runtime/mgc0.c:1383

goroutine 4 [finalizer wait]:
runtime.gopark(0x43e6d0, 0x9c9c10, 0x7f8890, 0xe)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/proc.go:130 +0x105 fp=0xc208019730 sp=0xc208019700
runtime.goparkunlock(0x9c9c10, 0x7f8890, 0xe)
	/usr/local/Cellar/go/1.4/libexec/src/runtime/proc.go:136 +0x48 fp=0xc208019758 sp=0xc208019730
runtime.runfinq()
	/usr/local/Cellar/go/1.4/libexec/src/runtime/malloc.go:727 +0xba fp=0xc2080197e0 sp=0xc208019758
runtime.goexit()
	/usr/local/Cellar/go/1.4/libexec/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080197e8 sp=0xc2080197e0
created by runtime.createfing
	/usr/local/Cellar/go/1.4/libexec/src/runtime/malloc.go:707 +0x5e
```

**Comment by rcshubhadeep** [comment]
with a ubuntu 16.04 I faced the same problem. I re compiled with Go 1.7.4 and then used that binary instead of the official one and it did not give me this error anymore. So I guess it is indeed linked to [this](https://github.com/golang/go/issues/9191) issue. But I guess compiling the release binary in a later version of Go will help remove this one. What do you think?

**Comment by CatTail** [comment]
@rcshubhadeep I build a new version with Go1.7.5, please verify if this works https://github.com/git-hooks/git-hooks/releases/tag/v1.1.4

**Comment by rcshubhadeep** [comment]
This one works perfectly. I believe you should make a new release. 

Thanks a lot!
